apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: temperature-monitoring
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin123"

  # RabbitMQ credentials
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "admin123"
