apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-principal
  namespace: temperature-monitoring
spec:
  rules:
    - host: temperature-monitoring.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-principal
                port:
                  number: 3000
