apiVersion: v1
kind: Service
metadata:
  name: api-principal
  namespace: temperature-monitoring
spec:
  selector:
    app: api-principal
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
